apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::856138947334:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-VLLZXQV4DGIB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::856138947334:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-15T13:26:13Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1510"
  uid: 38f00478-6c18-4e63-b641-b01f2ecbc632
