apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-demo-deployment
  labels:
    app: flask-app-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: flask-app-demo
    spec:
      containers:
        - name: flask-app-demo
          # image: abdullahi7788/flask-app-demo
          image: abdullahi7788/flask-app-demo
          securityContext:
            privileged: false
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          ports:
            - containerPort: 8080
